apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: mafilvv0o-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-58fcdbdea4.jaj7.p3.openshiftapps.com/rhtap/rhtap-qe:4f3c4f8dcf561d3b6673ef1d6d3aaa915184bf99@sha256:c99a1a96740a590ecd4bc15bbad990fe679fd719bfa7e81f6ace818b29838255
        name: container-image  
